const TypeMaintenance = {
    VIDANGE: 'VIDANGE',
    REVISION: 'REVISION',
    CHANGEMENT_PNEUS: 'CHANGEMENT_PNEUS',
    FREINS: 'FREINS',
    ELECTRIQUE: 'ELECTRIQUE',
    CARROSSERIE: 'CARROSSERIE',
    CONTROLE_TECHNIQUE: 'CONTROLE_TECHNIQUE'
};

module.exports = TypeMaintenance;
